### ISSUE TITLE
How to recompile library?

### ISSUE THREAD

**Issue by BruceInCalgary** [RIDICS/Loading-Visualization#1]
I am a newbie web programmer and am using ASP.NET Core for a web app. I would like to change the default color used for the circles in your library.  However, I am not sure how to use gulp and yarn.  I ran "npm install gulp-yarn --save-dev" and then tried to recompile using "yarn gulp" but received the error that yarn is not a recognized command.  I have been doing some Googling but haven't found information to help with this.  Can you help or point me to some information that would be useful for me?  Thank you!

**Comment by vladapokorny** [comment]
Hi, firstly you should decide if you want to use Yarn or NPM for restoring dependencies. We prefer Yarn therefore yarn.lock file is committed in the repository. Yarn or NodeJS (for NPM) must be installed as standalone application on the computer.

Steps for build:
1. Restore developer dependencies: `yarn install`
2. Run gulp task to compile the library `yarn gulp`

That's all.

**Comment by BruceInCalgary** [comment]
Thank you Vladimir, I really appreciate your help!  And great work on the loading spinners!

 

Best regards, Bruce

 

Bruce Tompkins

(  (403) 399-3871

(  1-888-266-4381 (toll free)

* bruce.tompkins@spiritofcomputing.com

Member of Sukyo Mahikari Since 1993

**Comment by vladapokorny** [comment]
You're welcome

**Comment by BruceInCalgary** [comment]
Hi Vladimir,

 

After recompiling and adding the spinner to my Razor page, the text appears but no spinners (using the circles)? Should I open another thread on GitHub about this?  

 

Best regards, Bruce

 

Bruce Tompkins

(  (403) 399-3871

(  1-888-266-4381 (toll free)

* bruce.tompkins@spiritofcomputing.com

Member of Sukyo Mahikari Since 1993

**Comment by vladapokorny** [comment]
Hi, sorry for the slow reaction. If you still have a problem, please open a new issue with more detail description and we will look at it. It is hard to guess where is the problem without details because everything looks good on the demo page.

**Comment by BruceInCalgary** [comment]
Thanks Vladimir,

 

I’ll look at this again before I post anything.  The demo page does run correctly on my PC = so am not sure why it doesn’t run on my Razor page.  No errors coming up either.  Will let you know if I find something that others might need to know or if it’s a silly mistake on my part! J  Have a very merry Christmas!

 

Best regards, Bruce

 

Bruce Tompkins

(  (403) 399-3871

(  1-888-266-4381 (toll free)

* bruce.tompkins@spiritofcomputing.com

Member of Sukyo Mahikari Since 1993
